### ISSUE TITLE
twil.io not twilio.io

### ISSUE THREAD

**Issue by andrewpatterson3001** [TwilioDevEd/client-quickstart-js#1]
https://github.com/TwilioDevEd/client-quickstart-js/blob/eb46d3fad1ede371e7a49dd97fb6a2bacfa002bd/public/quickstart.js#L9

Should be SUBDOMAIN.twil.io not SUBDOMAIN.twilio.io

**Comment by atbaker** [comment]
Fixed in https://github.com/TwilioDevEd/client-quickstart-js/commit/fc2f01d5f489bc114fef6b9f94c750d312325dc8. Thanks Andrew!
